/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'TriggerPharosCheckin': ApiRouteHandler<{ id: string }, ApiResponse<200, { ok: boolean; id: string }> | ApiResponse<400, { error: string }>, { topic: 'pharos-checkin'; data: { id: string } }>
    'PharosSchedule': CronHandler<{ topic: 'pharos-checkin'; data: { id: string } }>
    'PharosCheckIn': EventHandler<{ id: string }, never>
    'WalletEncrypt': ApiRouteHandler<{ private_key?: string; mnemonic?: string }, ApiResponse<200, { encrypted_private_key?: string; encrypted_mnemonic?: string }> | ApiResponse<400, { error: string }> | ApiResponse<503, { error: string }>, never>
    'WalletCreate': ApiRouteHandler<{ wallet_type: 'evm' | 'solana'; count: unknown }, ApiResponse<200, { created: number; ids: Array<string>; addresses: Array<string> }> | ApiResponse<400, { error: string }> | ApiResponse<503, { error: string }>, never>
  }
    
}